angular
    .module('diputadosweb',['ngRoute'])
    .config(
        function($routeProvider){
            $routeProvider
            .when('/',{templateUrl:'views/view.notfound.html',controller:'notFoundCtrl'})
            .when('/:id',{templateUrl:'views/view.index.html',controller:'indexCtrl'})
            .when('/notfound',{templateUrl:'views/view.notfound.html',controller:'notFoundCtrl'})
            .otherwise({redirectTo:'/'});
        }
    );